# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Linh Le
tagline:          'my personal website'
description:      'Welcome to my personal website'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Linh Le'
  url:            https://twitter.com/Manh_Linh_Le

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aidenva/aidenva.github.io
