# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-REZN819YX1'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Music',   url: 'music.html'}
- {name: 'Writing', url: 'writing.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter',    link: 'https://twitter.com/Manh_Linh_Le'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/manhlinhle/'}
- {icon: 'envelope',   link: 'mailto:linh.le@yale.edu'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
